services:
  # minecraft1
  # minecraft2
  web1: 
    image: corentinth/it-tools@sha256:8b8128748339583ca951af03dfe02a9a4d7363f61a216226fc28030731a5a61f 
    container_name: web1
    restart: unless-stopped
    ports:
      - '5000:80'
    networks:
      - sockets_app

  web2:
    image: corentinth/it-tools@sha256:8b8128748339583ca951af03dfe02a9a4d7363f61a216226fc28030731a5a61f 
    container_name: web2
    restart: unless-stopped
    ports:
      - '5001:80'
    networks:
      - sockets_app

  load-bal:
    build: .
    container_name: load-bal
    restart: unless-stopped
    env_file: .env
    ports:
      - '8000:8000'
    networks:
      - sockets_app

networks:
  sockets_app:
